sudo: required
addons:
    apt:
      packages:
        - cmake
      sources:
        - kalakris-cmake

language: c

compiler:
  - gcc
  - clang

script: mkdir bld && cd bld && cmake .. && cmake --build . 

